/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Menu;


/**
 *
 * @author Admin
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form VentanaPrincipal
     */
    
    public VentanaPrincipal() {
        initComponents();           
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        textoBienvenida = new javax.swing.JLabel();
        fondoGif = new javax.swing.JLabel();
        menuprincipal = new javax.swing.JMenuBar();
        Menu = new javax.swing.JMenu();
        menuPila = new javax.swing.JMenu();
        submenuPila1 = new javax.swing.JMenu();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        submenuPila2 = new javax.swing.JMenu();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        menuCola = new javax.swing.JMenu();
        submenuCola1 = new javax.swing.JMenu();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        submenuCola2 = new javax.swing.JMenu();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        menuLista = new javax.swing.JMenu();
        submenuLista1 = new javax.swing.JMenu();
        jSeparator5 = new javax.swing.JPopupMenu.Separator();
        submenuLista3 = new javax.swing.JMenu();
        jSeparator6 = new javax.swing.JPopupMenu.Separator();
        submenuListaDoblemente = new javax.swing.JMenu();
        jSeparator7 = new javax.swing.JPopupMenu.Separator();
        submenuLista4 = new javax.swing.JMenu();
        menuAyuda = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ESTRUCTURAS LINEALES");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setExtendedState(MAXIMIZED_BOTH);

        textoBienvenida.setBackground(new java.awt.Color(255, 255, 51));
        textoBienvenida.setForeground(new java.awt.Color(0, 153, 204));
        textoBienvenida.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        textoBienvenida.setText("BIENVENIDO USUARIO LISTO PARA INICIAR... ");
        textoBienvenida.setAutoscrolls(true);
        textoBienvenida.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        fondoGif.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fondoGif.setLabelFor(this);
        fondoGif.setToolTipText("");
        fondoGif.setAutoscrolls(true);

        menuprincipal.setAutoscrolls(true);
        menuprincipal.setMinimumSize(new java.awt.Dimension(100, 200));

        Menu.setText("Crear   ");

        menuPila.setText("PILA");

        submenuPila1.setText("ESTATICA");
        submenuPila1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                submenuPila1MouseClicked(evt);
            }
        });
        menuPila.add(submenuPila1);
        menuPila.add(jSeparator1);

        submenuPila2.setText("DINAMICA");
        submenuPila2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                submenuPila2MouseClicked(evt);
            }
        });
        menuPila.add(submenuPila2);

        Menu.add(menuPila);
        Menu.add(jSeparator2);

        menuCola.setText("COLA");

        submenuCola1.setText("ESTATICA");
        menuCola.add(submenuCola1);
        menuCola.add(jSeparator4);

        submenuCola2.setText("DINAMICA");
        menuCola.add(submenuCola2);

        Menu.add(menuCola);
        Menu.add(jSeparator3);

        menuLista.setText("LISTA");

        submenuLista1.setText("SIMPLEMENTE ENLAZADA");
        menuLista.add(submenuLista1);
        menuLista.add(jSeparator5);

        submenuLista3.setText("SIMPLEMENTE ENLAZADA CIRCULAR");
        menuLista.add(submenuLista3);
        menuLista.add(jSeparator6);

        submenuListaDoblemente.setText("DOBLEMENTE ENLAZADA");
        submenuListaDoblemente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                submenuListaDoblementeMouseClicked(evt);
            }
        });
        menuLista.add(submenuListaDoblemente);
        menuLista.add(jSeparator7);

        submenuLista4.setText("DOBLEMENTE ENLAZADA CIRCULAR");
        menuLista.add(submenuLista4);

        Menu.add(menuLista);

        menuprincipal.add(Menu);

        menuAyuda.setText("Ayuda");
        menuprincipal.add(menuAyuda);

        setJMenuBar(menuprincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(textoBienvenida, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(fondoGif)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(textoBienvenida, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(fondoGif, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void submenuPila1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_submenuPila1MouseClicked
        // TODO add your handling code here:
        MenuPilaEstatica objMenuPilaE = new MenuPilaEstatica();
        objMenuPilaE.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_submenuPila1MouseClicked

    private void submenuPila2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_submenuPila2MouseClicked
        // TODO add your handling code here:
        MenuPilaDinamica objMenuPilaD = new MenuPilaDinamica ();
        objMenuPilaD.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_submenuPila2MouseClicked

    private void submenuListaDoblementeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_submenuListaDoblementeMouseClicked
        // TODO add your handling code here:
        MenuListaDoblementeEnlazada objetoLDE = new MenuListaDoblementeEnlazada();        
        objetoLDE.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_submenuListaDoblementeMouseClicked

    /**
     * @param args the command line arguments
     */
    
    public static void main(String args[]) {
     
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);               
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Menu;
    private javax.swing.JLabel fondoGif;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JPopupMenu.Separator jSeparator5;
    private javax.swing.JPopupMenu.Separator jSeparator6;
    private javax.swing.JPopupMenu.Separator jSeparator7;
    private javax.swing.JMenu menuAyuda;
    private javax.swing.JMenu menuCola;
    private javax.swing.JMenu menuLista;
    private javax.swing.JMenu menuPila;
    private javax.swing.JMenuBar menuprincipal;
    private javax.swing.JMenu submenuCola1;
    private javax.swing.JMenu submenuCola2;
    private javax.swing.JMenu submenuLista1;
    private javax.swing.JMenu submenuLista3;
    private javax.swing.JMenu submenuLista4;
    private javax.swing.JMenu submenuListaDoblemente;
    private javax.swing.JMenu submenuPila1;
    private javax.swing.JMenu submenuPila2;
    private javax.swing.JLabel textoBienvenida;
    // End of variables declaration//GEN-END:variables
}
